### ISSUE TITLE
 CWE-203: Observable Discrepancy(team 4) 

### ISSUE THREAD

**Issue by atia98** [ELG7186-s22/project-group-2#13]
a malicious actor can use brute-force techniques (by using large world-list such as rockyou) to either guess or confirm valid usernames in your web Application.
![WhatsApp Image 2022-08-05 at 3 31 05 AM](https://user-images.githubusercontent.com/57109699/182982539-f8d64516-10d9-40a5-83eb-d609ba6b00b6.jpeg)

**Comment by AhmedYHamza** [comment]
Thank you for your feedback. But, actually this is not a problem as between the capcha and the strong password requirements it would be considerably difficult to produce a brute force attack. Furthermore, this issue is very hard to avoid as the users need to know whether a username is available or not.
